#!/usr/bin/env node

//
// SPDX-License-Identifier: AGPL-3.0-or-later
//

const
  _fs_utils =
    require(
      "./fs-utils");
_basename =
  _fs_utils._basename


function
  _app_name_get() {
  let
    _filename;
  _filename =
    _basename(
      __filename);
  return _filename;
}


function 
  _msg_template(
    _app_name,
    _type) {
  let
    _out,
    _partial,
    _template;
  _template =
    "[{_app_name}] {_type}: {_msg}"
  _partial =
    _template.replaceAll(
      "{_app_name}",
      _app_name);
  _out =
    _partial.replaceAll(
      "{_type}",
      _type);
  return _out;
}


function
  _msg_info(
    _msg) {
  let
    _out;
  if ( quiet == "n" ) {
    _template =
      _msg_template(
	app_name,
        'INFO');
    _out =
      _template.replaceAll(
        "{_msg}",
        _msg);
    console.log(
      _out);
  }
}


function
  _msg_error(
    _msg,
    _exit) {
  let
    _template,
    _out;
  _template =
    _msg_template(
      app_name,
      'ERROR');
  _out =
    _template.replaceAll(
      "{_msg}",
      _msg);
  console.error(
    _out);
  if (_exit == "1" ) {
    process.exit();
  }
}


function 
  _msg_info_obj(
    _name,
    _obj) {
  let
    _template,
    _partial,
    _msg;
  _template =
    "{_name} '{_obj}'"
  _partial =
    _template.replaceAll(
      "{_name}",
      _name);
  _msg =
    _partial.replaceAll(
      "{_obj}",
      _obj);
  _msg_info(
    _msg);
}


module.exports = {
  _app_name_get:
    _app_name_get,
  _basename:
    _fs_utils._basename,
  _dirname:
    _fs_utils._dirname,
  _file_exists:
    _fs_utils._file_exists,
  _file_read:
    _fs_utils._file_read,
  _msg_info:
    _msg_info,
  _msg_error:
    _msg_error,
  _msg_info_obj:
    _msg_info_obj,
};
