#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later

/**    ----------------------------------------------------------------
 *     crash-js
 *     ----------------------------------------------------------------
 *     Copyright ©
 *       Pellegrino Prevete
 *         2024, 2025, 2026
 * 
 *     All rights reserved
 *     ----------------------------------------------------------------
 * 
 *     This program is free software: you can redistribute it and/or
 *     modify it under the terms of the GNU General Public License as
 *     published by the Free Software Foundation, either version 3 of
 *     the License, or (at your option) any later version.
 * 
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the GNU General Public
 *     License along with this program.
 *     If not, see <https://www.gnu.org/licenses/>.
 */

const
_utils =
  require(
    "./utils");
const
_argv_get =
  _utils._argv_get;
const
_argv_url_get =
  _utils._argv_url_get;
const
_child_process_spawn_get =
  _utils._child_process_spawn_get;
const
  _spawn =
    _child_process_spawn_get();
const
  _spawn_async =
    _child_process_spawn_get(
      "async");
const
  _process_exit_get =
    _utils._process_exit_get;
const
  _process_exit =
    _process_exit_get();
const
  _process_cwd_get =
    _utils._process_cwd_get;
const
  _process_cwd =
    _process_cwd_get();
const
  _pwd =
    _process_cwd;
const
  _yargv_get =
    _utils._yargv_get;
const
  _fs_utils_module =
    require(
      "./fs-utils");
const
  _basename =
    _fs_utils_module._basename;
const
  _dirname =
    _fs_utils_module._dirname;
const
  _file_append =
    _fs_utils_module._file_append;
const
  _file_exists =
    _fs_utils_module._file_exists;
const
  _path_join =
    _fs_utils_module._path_join;
const
  _stat =
    _fs_utils_module._stat;

function
  _globals() {
  app_name =
    "";
  quiet =
    "y";
  }

function
  _app_name_get() {
  let
    _filename;
  _filename =
    _basename(
      __filename);
  return _filename;
}

function 
  _msg_template(
    _type,
    _app_name) {
  let
    _template;
  if ( typeof(
         _app_name) == "undefined" ||
       _app_name == "" ) {
    _template =
      `${_type}: {_msg}`;
  }
  else if ( typeof(
              _app_name) == "string" ||
            _app_name != "" ) {
      _template =
        `[${_app_name}] ${_type}: {_msg}`;
  }
  return _template;
}

function
  _msg_warning(
    _msg) {
  let
    _out;
  if ( quiet == "n" ) {
    _template =
      _msg_template(
        "WARNING",
        app_name);
    _out =
      _template.replaceAll(
        "{_msg}",
        _msg);
    console.warn(
      _out);
  }
}

function
  _msg_info(
    _msg) {
  let
    _out;
  if ( typeof(
         quiet) == "undefined" ||
       quiet == "" ) {
    quiet =
      "y";
  }
  if ( quiet == "n" ) {
    const
      _template =
        _msg_template(
          "INFO",
          app_name);
    _out =
      _template.replaceAll(
        "{_msg}",
        _msg);
    console.log(
      _out);
  }
}

function
  _msg_error(
    _msg,
    _exit) {
  let
    _template,
    _out;
  if ( typeof(
         app_name) == "undefined" ||
         app_name == "" ) {
    const
      app_name =
        "";
  }
  _exit =
    String(
      _exit);
  _template =
    _msg_template(
      "ERROR",
      app_name);
  _out =
    _template.replaceAll(
      "{_msg}",
      _msg);
  if ( _exit === "1" ) {
    console.error(
      _out);
    _process_exit(
      1);
  }
  else if ( _exit === "0" ) {
    console.warn(
      _out);
  }
}

function 
  _msg_info_obj(
    _name,
    _obj) {
  let
    _template,
    _partial,
    _msg;
  _msg =
    `${_name}: '${_obj}'`;
  _msg_info(
    _msg);
}

function
  _error_display(
    _error) {
  let
    _message;
  if ( typeof(error) == "object" ) {
    if ( 'error' in _error && 
         _error[
           'error'] != undefined &&
         'message' in _error[
                        'error'] ) {
      _message =
        _error[
          'error'][
            'message'];
    }
    else if ( 'shortMessage' in _error ) {
      _message =
        _error[
          'shortMessage'];
    }
    else {
      _message =
        _error;
    }
    console.error(
      _error);
  }
  else {
    _message =
      _error;
    console.error(
      _error);
  }
  _msg_error(
    _message,
    0);
}

function
  _cmdline_check(
    _app_name) {
  let
    _argv,
    _program,
    _program_name;
  if ( typeof window === 'undefined' ) {
    _argv =
      _argv_get();
    _program =
      _argv[
        1];
    if ( typeof(
           _program) === 'undefined' ) {
      _program =
        _argv[
          "$0"];
    }
    _program_name =
      _basename(
        _program);
    if ( _program_name == _app_name ) {
      return true;
    }
    else {
      return false;
    }
  }
  else {
    return false;
  }
}

function
  _get_date_human() {
  const
    _date =
      new Date();
  const
    _year =
      _date.getFullYear();
  const
    _month =
      _date.getMonth();
  const
    _day =
      _date.getDay();
  const
    _time =
      `${_date.getHours()}:${_date.getMinutes()}`;
  // Assume UTC
  const
    _zone =
      "0000"
  const
    _date_human =
      `${_year}-${_month}-${_day}T${_time}+${_zone}`;
  return _date_human;
}

// This function is actually not a format
// print, but just how the author of this
// library calls a display function which
// does not add a goddamn newline at the
// end of the input text to display
function
  _printf(
    _text) {
  let
    _stdout_write;
  if ( typeof window === 'undefined' ) {
    _stdout =
      process.stdout;
  }
  if ( typeof window != 'undefined' ) {
    _stdout =
      require(
        "stream-browserify");
  }
  _stdout.write(
    _text);
}

function
  _homedir_get() {
  let
    _home;
  if ( typeof window === 'undefined' &&
       ( typeof global !== 'undefined' && global.global === global ) &&
       typeof __webpack_require__ !== 'function' ) {
    _home =
      process.env.HOME;
  }
  if ( typeof(
         window) != "undefined" ) {
    _home =
      "/home/user";
  }
  return _home;
}

async function
  _lib_get() {
  let
    _lib,
    _lib_path,
    _line,
    _out,
    _path,
    _words;
  const
    _paths =
      new Set();
  if ( typeof window === 'undefined' &&
       ( typeof global !== 'undefined' && global.global === global ) &&
       typeof __webpack_require__ !== 'function' ) {
    const
      _out =
        await _run(
         "sync",
          [ "ldconfig",
            "-p" ]);
    // console.log(_out);
    const
      _tail =
        _out.slice(
          1,
          _out.length - 2);
    for ( _line of _tail ) {
      _words =
        _line.split(" ");
      _lib_path =
        _words[
          3];
      _lib =
        _dirname(
          _lib_path);
      _paths.add(
        _lib);
    }
    if ( typeof(
           process.env.NODE_PATH) == "undefined" ||
         process.env.NODE_PATH == "" ) {
      const
        _msg =
          "Environment variable NODE_PATH undefined.";
      _msg_info(
        _msg);
    }
    else {
      _lib =
        _path_join(
          [ process.env.NODE_PATH,
            "../lib" ]);
      if ( _file_exists(
             _lib) ) {
        _paths.add(
          _lib);
      }
    }
    for ( _path of _paths ) {
      return _path;
    }
  }
  else {
    _lib =
      "/usr/lib";
  }
  return _lib
}

function
  _echo(
    _text) {
  console.log(
    _text);
}

function
  _range(
    _start,
    _end) {
  let
    _length;
  if ( typeof(
         _end) === 'undefined' ) {
    _end =
      _start;
    _start =
      0;
  }
  _length =
    _end -
    _start;
  if ( _length < 0 ) {
    _msg =
      `Second argument 'end' ` +
      `is greater than first ` +
      `argument 'start', returning ` +
      `empty list.`;
    _msg_warning(
      _msg);
    return [];
  }
  return Array(
           _length).keys().map(
             _index =>
               _index + _start);
}

async function
  _run(
    _run_mode,
    _cmd,
    _name,
    _timeout,
    _run_type,
    _method) {
  let
    _array,
    _index,
    _msg,
    _out;
  if ( typeof(
         _cmd) == "undefined" ||
       _cmd == "" ||
       _cmd == [] ) {
    _msg =
      "No command given in input.";
    _msg_error(
        _msg,
        1);
  }
  const
    _program =
      _cmd[
        0];
  const
    _args =
      _cmd.slice(
        1,
        _cmd.length);
  if ( typeof(
         _run_mode) == "undefined" ||
       _run_mode == "" ) {
    _run_mode =
      "sync";
  }
  if ( typeof(
         _name) == "undefined" ||
       _name == "" ) {
    _name =
      "";
  }
  if ( typeof(
         _timeout) == "undefined" ||
       _timeout == "" ) {
    _timeout =
      "0";
  }
  if ( typeof(
         _run_type) == "undefined" ||
       _run_type == "" ) {
    _run_type =
      "spawn";
  }
  if ( typeof(
         _method) == "undefined" ||
       _method == "" ) {
    _method =
      "";
  }
  _msg =
    `Running '${_program}' ` +
    `with arguments '${_args}'.`;
  _msg_info(
    _msg);
  _out =
    "";
  if ( _run_mode == "async" ) {
    // currently not working well id say
    const
      _print =
        function
          (_data) {
          _out = 
            _out +
            _data.toString();
        };
    const
      _close =
        function(
          _code) {
          let
            _array,
            _msg;
          if ( _code != 0 ) {
            _msg =
              `Process exited with code '${_code}'`;
            _msg_error(
              _msg,
              1);
          }
          else {
            _msg =
              `Process exited normally.`;
            _msg_info(
              _msg);
          }
          _array =
            _out.split("\n");
          return _array;
        };
    const
      _process =
        _spawn_async(
          _program,
          _args);
    _process.stdout.on(
      'data',
      _print);
    _process.on(
      'close',
      _close);
    _array =
      _out.split(
        "\n");
    _msg_info(
      _array.length);
    return _array;
  }
  else if ( _run_mode == "sync" ) {
    if ( _run_type == "spawn" ) {
      const
        _process =
          _spawn(
            _program,
            _args,
            { "encoding":
                "utf-8" });
      _array =
        _process.stdout.split(
          "\n");
      return _array;
    }
    else if ( _run_type == "native" ) {
      if ( 0 < _timeout ) {
        _msg_timeout =
          `Timeout of length ` +
          `'${_timeout}' ms reached for task '${_name}'.`;
        _time_over =
          false;
        try {
          const
            _timeout_promise =
              new Promise(
	        (resolve,
                 reject) => {
                  setTimeout(
                    () => {
                      return;
                    },
                    _timeout,
                    "hurr")
                });
          if ( _method != "" ) {
            _out =
              await Promise.race( [
                _sleep(
                  _timeout),
                  _program[
                    _method].apply(
                    _program,
                    _args)
	      ]);
            if ( typeof(
                   _out) == "undefined" ) {
              throw _msg_timeout;
	    }
          }
          else {
            _out =
              await _program.apply(
                _program,
                _args);
          }
        }
        catch(
          _error) {
          _time_over =
            true;
        }
        if ( _time_over ) {
          _msg_warning(
            _msg_timeout);
          return;
        }
        else {
          return _out;
        }
      }
      else {
        _out =
          await _program[
            _method].apply(
            _program,
            _args);
      }
    }
  }
}

function
  _seq(
    _start,
    _end) {
  let
    _item,
    _list;
  _list =
    [];
  if ( _end < _start ) {
    _msg =
      `Second argument 'end' ` +
      `is greater than first ` +
      `argument 'start', returning ` +
      `empty list.`;
    _msg_warning(
      _msg);
    return _list;
  }
  if ( typeof(
         _end) === 'undefined' ) {
    _end =
      _start;
    _start =
      1;
  }
  for ( _item of _range(
                   _start,
                   _end + 1) ) {
    _list.push(
      _item);
  }
  return _list;
}

function
  _sleep(
    _time) {
  return new Promise(
               resolve => setTimeout(
                            resolve,
                            _time));
}

function
  _from_bash_ass_array(
    _bash_array_string) {
  let
    _array,
    _array_name,
    _array_content_re,
    _array_content,
    _array_keys,
    _array_values,
    _key,
    _key_re,
    _keys_matches,
    _keys_re,
    _msg,
    _string,
    _value,
    _value_matches,
    _value_match;
  const
    _array_names =
      [];
  const
    _return =
      {};
  const
    _array_names_re =
      new RegExp(
        `(.+)=\\(`,
        "g");
  const
    _arrays_strings =
      _bash_array_string.match(
        _array_names_re);
  for ( _string of _arrays_strings ) {
    _array_name =
      _string.replace(
        "=(",
        "");
    _array_names.push(
      _array_name);
  }
  for ( _array_name of _array_names ) {
    _return[
      _array_name] =
      {};
    _array_content_re =
      new RegExp(
        `${_array_name}=\\(((.|\n)*?)\\)\n`,
        "g");
    _array_content =
      _bash_array_string.match(
        _array_content_re);
    if ( 1 < _array_content.length ) {
      _msg =
        "Multiple array " +
        `'${_array_name}' definitions ` +
        "detected.";
      _msg_error(
        _msg,
        1);
    }
    else if ( 0 < _array_content.length ) {
      _array =
        _array_content[
          0];
    }
    else {
      _msg =
        "No arrays found in input string.";
      _msg_error(
        _msg,
        1);
    }
    _keys_re =
      new RegExp(
        `\\["(.*?)"\\]`,
        "g");
    _keys_matches =
      _array.match(
        _keys_re);
    _array_keys =
      [];
    for ( _key of _keys_matches ) {
      _key_name =
        _key.replace(
          `["`,
          "");
      _key_name =
        _key_name.replace(
          `"]`,
          "");
      _array_keys.push(
        _key_name);
    }
    for ( _key of _array_keys ) {
      _value_re =
        new RegExp(
          `\\["${_key}"\\]="(.*?)"`,
          "g");
      _value_assignment_matches =
        _array.match(
          _value_re);
      if ( 1 < _value_assignment_matches.length ) {
        _msg =
          "Multiple values " +
          `'${_value_assignment_matches}' assignments found for ` +
          `key '${_key}' of associative array ` +
          `'${_array_name}'.`;
        _msg_error(
          _msg,
          1);
      }
      else if ( 0 < _value_assignment_matches.length ) {
        _value_assignment =
          _value_assignment_matches[
            0];
      }
      else {
        _msg =
          `No values found for key '${_key}'.`;
        _msg_error(
          _msg,
          1);
      }
      _value =
        _value_assignment.replace(
          RegExp(
            `^\\["${_key}"\\]="`,
            "g"),
          "");
      _value =
        _value.replace(
          RegExp(
            `"$`,
            "g"),
          "");
      _return[
        _array_name][
          _key] =
        _value;
    }
  }
  return _return;
}

function
  _to_bash_ass_array(
    _object) {
  let
    _index,
    _key,
    _key_declaration,
    _return;
  _return = [
    "#!/usr/bin/env bash"
  ];
  const
    _arrays_assignments =
      [];
  const
    _arrays_names =
      Object.keys(
        _object);
  const
    _arrays_declaration = [
      "declare \\",
      "  -A \\",
    ];
  const
    _arrays_amount =
      _arrays_names.length;
  const
    _index_max =
      _arrays_amount - 1;
  const
    _indexes =
      _seq(
        0,
        _index_max);
  for ( _index of _indexes ) {
    _array_name =
      _arrays_names[
        _index];
    _array_declaration =
      `  ${_array_name}`;
    if ( _index != _index_max ) {
      _array_declaration +=
        ` \\`;
    }
    _arrays_declaration.push(
      _array_declaration);
    _array_assignment = [
      `${_array_name}=(`
    ];
    _object_keys =
      Object.keys(
        _object[
          _array_name]);
    for ( _key of _object_keys ) {
      _value =
        _object[
          _array_name][
            _key];
      _key_assignment =
        `  ["${_key}"]="${_value}"`;
      _array_assignment.push(
        _key_assignment);
    }
    _array_assignment.push(
      ")");
    _array_assignment_string =
      _array_assignment.join(
        "\n");
    _arrays_assignments.push(
      _array_assignment_string);
  }
  _return =
    _return.concat(
      _arrays_declaration);
  _return =
    _return.concat(
      _arrays_assignments);
  _return =
    _return.join(
      "\n");
  return _return;
}

function
  _global_get() {
  let
    _global;
  if ( typeof window === 'undefined' &&
       ( typeof global !== 'undefined' && global.global === global ) &&
       typeof __webpack_require__ !== 'function' ) {
    _global =
      global;
  }
  if ( typeof(
         window) != "undefined" ) {
    _global =
      window;
  }
  return _global;
}

function
  _get(
    _obj,
    _var) {
  _getter_setter_input_check(
    _obj,
    _var);
  const
    _global =
      _global_get();
  return _global[
    `${_obj}_${_var}`];
}

function
  _getter_setter_input_check(
    _obj,
    _var,
    _value) {
  if ( typeof(
         _obj) === "undefined" ||
       _obj == "" ) &&
     ( typeof(
         _var) === "undefined" ||
       _var == "" ) {
    const
      _msg =
        "Either one of the 'object' or the " +
        "'variable' arguments must be non-empty";
    _msg_error(
      _msg,
      1);
  }
  if ( typeof(
         _value) === "undefined" ) {
    _value =
      "";
  }
}

function
  _set(
    _obj,
    _var,
    _value) {
  _getter_setter_input_check(
    _obj,
    _var);
  const
    _global =
      _global_get();
  _global[
    `${_obj}_${_var}`] =
    _value;
}

function
  _override_set(
    _obj,
    _var,
    _default) {
  _getter_setter_input_check(
    _obj,
    _var,
    _default);
  const
    _global =
      _global_get();
  if ( Object.keys(
         _global).includes(
           `override_${_obj}_${_var}`) {
    _set(
      _obj,
      _var,
      _get(
        `override_${_obj}`,
        `${_var}`));
  }
  else {
    _set(
      _obj,
      _var,
      _default)
  }
}

const
  _set_override =
    _override_set;

module.exports = {
  _argv_get:
    _argv_get,
  _argv_url_get:
    _argv_url_get,
  _app_name_get:
    _app_name_get,
  _basename:
    _fs_utils_module._basename,
  _cat:
    _fs_utils_module._cat,
  _chmod:
    _fs_utils_module._chmod,
  _chown:
    _fs_utils_module._chown,
  _cmdline_check:
    _cmdline_check,
  _cp:
    _fs_utils_module._cp,
  _dirname:
    _dirname,
  _echo:
    _echo,
  _error_display:
    _error_display,
  _ext_rm:
    _fs_utils_module._ext_rm,
  _dir_exists:
    _fs_utils_module._dir_exists,
  _file_append:
    _fs_utils_module._file_append,
  _file_exists:
    _fs_utils_module._file_exists,
  _file_read:
    _fs_utils_module._file_read,
  _file_write:
    _fs_utils_module._file_write,
  _from_bash_ass_array:
    _from_bash_ass_array,
  _fs_worker_new:
    _fs_utils_module._fs_worker_new,
  _fs_worker_start:
    _fs_utils_module._fs_worker_start,
  _get:
    _get,
  _get_date_human:
    _get_date_human,
  _globals:
    _globals,
  _global_get:
    _global_get,
  _homedir_get:
    _homedir_get,
  _json_display:
    _fs_utils_module._json_display,
  _json_read:
    _fs_utils_module._json_read,
  _lib_get:
    _lib_get,
  _ls:
    _fs_utils_module._ls,
  _mkdir:
    _fs_utils_module._mkdir,
  _mktemp:
    _fs_utils_module._mktemp,
  _msg_info:
    _msg_info,
  _msg_error:
    _msg_error,
  _msg_warning:
    _msg_warning,
  _msg_info_obj:
    _msg_info_obj,
  _mv:
    _fs_utils_module._mv,
  _override_set:
    _override_set,
  _path_join:
    _path_join,
  _printf:
    _printf,
  _process_exit:
    _process_exit,
  _process_cwd:
    _process_cwd,
  _pwd:
    _pwd,
  _range:
    _range,
  _rm:
    _fs_utils_module._rm,
  _run:
    _run,
  _seq:
    _seq,
  _set:
    _set,
  _set_override:
    _set_override,
  _sleep:
    _sleep,
  _stat:
    _stat,
  _to_bash_ass_array:
    _to_bash_ass_array,
  _yargv_get:
    _yargv_get
};
