#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later

/**    ----------------------------------------------------------------
 *     crash-js
 *     ----------------------------------------------------------------
 *     Copyright ©
 *       Pellegrino Prevete
 *         2024, 2025, 2026
 * 
 *     All rights reserved
 *     ----------------------------------------------------------------
 * 
 *     This program is free software: you can redistribute it and/or
 *     modify it under the terms of the GNU General Public License as
 *     published by the Free Software Foundation, either version 3 of
 *     the License, or (at your option) any later version.
 * 
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the GNU General Public
 *     License along with this program.
 *     If not, see <https://www.gnu.org/licenses/>.
 */

const
  _fs_utils_module =
    await import(
      "./fs-utils");
/* global
     _argv */
const
  _argv =
    _fs_utils_module._argv;
/* global
     _basename */
const
  _basename =
    _fs_utils_module._basename;
/* global
     _cat */
const
  _cat =
    _fs_utils_module._cat;
/* global
     _child_process_spawn_get */
const
  _child_process_spawn_get =
    _fs_utils_module._child_process_spawn_get;
/* global
     _chmod */
const
  _chmod =
    _fs_utils_module._chmod;
/* global
     _chown */
const
  _chown =
    _fs_utils_module._chown;
/* global
     _cd */
const
  _cd =
    _fs_utils_module._cd;
/* global
     _cp */
const
  _cp =
    _fs_utils_module._cp;
/* global
     _chdir */
const
  _chdir =
    _fs_utils_module._cd;
/* global
     _cwd */
const
  _cwd =
    _fs_utils_module._cwd;
/* global
     _dir_exists */
const
  _dir_exists =
    _fs_utils_module._dir_exists;
/* global
     _dirname */
const
  _dirname =
    _fs_utils_module._dirname;
/* global
     _exit */
const
  _exit =
    _fs_utils_module._exit;
/* global
     _ext_rm */
const
  _ext_rm =
    _fs_utils_module._ext_rm;
/* global
     _file_append */
const
  _file_append =
    _fs_utils_module._file_append;
/* global
     _file_exists */
const
  _file_exists =
    _fs_utils_module._file_exists;
/* global
     _file_read */
const
  _file_read =
    _fs_utils_module._file_read;
/* global
     _file_write */
const
  _file_write =
    _fs_utils_module._file_write;
/* global
     _fs_worker_new */
const
  _fs_worker_new =
    _fs_utils_module._fs_worker_new;
/* global
     _fs_worker_start */
const
  _fs_worker_start =
    _fs_utils_module._fs_worker_start;
/* global
     _json_display */
const
  _json_display =
    _fs_utils_module._json_display;
/* global
     _json_read */
const
  _json_read =
    _fs_utils_module._json_read;
/* global
     _lib_get */
const
  _lib_get =
    _fs_utils_module._lib_get;
/* global
     _ls */
const
  _ls =
    _fs_utils_module._ls;
/* global
     _mkdir */
const
  _mkdir =
    _fs_utils_module._mkdir;
/* global
     _mktemp */
const
  _mktemp =
    _fs_utils_module._mktemp;
/* global
     _mv */
const
  _mv =
    _fs_utils_module._mv;
/* global
     _path_join */
const
  _path_join =
    _fs_utils_module._path_join;
/* global
     _printf */
const
  _printf =
    _fs_utils_module._printf;
/* global
     _pwd */
const
  _pwd =
    _fs_utils_module._pwd;
/* global
     _require */
const
  _require =
    _fs_utils_module._require;
/* global
     _rm */
const
  _rm =
    _fs_utils_module._rm;
/* global
     _source */
const
  _source =
    _fs_utils_module._source;
/* global
     _spawn */
const
  _spawn =
    await _child_process_spawn_get();
/* global
     _spawn_async */
const
  _spawn_async =
    await _child_process_spawn_get(
      "async");
/* global
     _stat */
const
  _stat =
    _fs_utils_module._stat;
/* global
     _usr_get */
const
  _usr_get =
    _fs_utils_module._usr_get;
/* global
     _os_tmpdir */
const
  _os_tmpdir =
    await _fs_utils_module._os_tmpdir_get();
/* global
     _utils */
const
  _utils =
    await _require(
      "./utils");
// const
//   _utils =
//     _utils_module.default;
/* global
     _argv_url_get */
const
  _argv_url_get =
    _utils._argv_url_get;
/* global
     _display_error */
const
  _display_error =
    _utils._display_error;
/* global
     _error_display */
const
  _error_display =
    _display_error;
/* global
     _global_get */
const
  _global_get =
    _utils._global_get;
/* global
     _msg_info */
const
  _msg_info =
    _utils._msg_info;
/* global
     _msg_info_obj */
const
  _msg_info_obj =
    _utils._msg_info_obj;
/* global
     _msg_error */
const
  _msg_error =
    _utils._msg_error;
/* global
     _msg_template */
const
  _msg_template =
    _utils._msg_template;
/* global
     _msg_warning */
const
  _msg_warning =
    _utils._msg_warning;
const
  _split_module =
    _require(
      "split");
/* global
     _split */
const
  _split =
    _split_module._split;

async function
  _argv_get(
    _args) {
  let
    _argv;
  if ( typeof window === 'undefined' &&
       ( typeof global !== 'undefined' && global.global === global ) &&
       typeof __webpack_require__ !== 'function' ) {
    _argv =
      await _yargv_get(
        _args);
  }
  else {
    _argv =
      _argv_url_get();
  }
  return _argv;
}

function
  _app_name_get() {
  let
    _filename;
  _filename =
    _basename(
      __filename);
  return _filename;
}

async function
  _cmdline_check(
    _app_name) {
  let
    _argv,
    _program,
    _program_name;
  if ( typeof window === 'undefined' ) {
    _argv =
      await _argv_get();
    _program =
      _argv[
        1];
    if ( typeof(
           _program) === 'undefined' ) {
      _program =
        _argv[
          "$0"];
    }
    _program_name =
      _basename(
        _program);
    if ( _program_name == _app_name ) {
      return true;
    }
    else {
      return false;
    }
  }
  else {
    return false;
  }
}

function
  _get_date_human() {
  const
    _date =
      new Date();
  const
    _year =
      _date.getFullYear();
  const
    _month =
      _date.getMonth();
  const
    _day =
      _date.getDay();
  const
    _time =
      `${_date.getHours()}:${_date.getMinutes()}`;
  // Assume UTC
  const
    _zone =
      "0000"
  const
    _date_human =
      `${_year}-${_month}-${_day}T${_time}+${_zone}`;
  return _date_human;
}

/* global
     _get_lib */
const
  _get_lib =
    _lib_get;

/* global
     _get_usr */
const
  _get_usr =
    _usr_get;

function
  _homedir_get() {
  let
    _home;
  if ( typeof window === 'undefined' &&
       ( typeof global !== 'undefined' && global.global === global ) &&
       typeof __webpack_require__ !== 'function' ) {
    _home =
      process.env.HOME;
  }
  if ( typeof(
         window) != "undefined" ) {
    _home =
      "/home/user";
  }
  return _home;
}

const
  _echo =
    console.log;

const
  _echo2 =
    console.error;

function
  _range(
    _start,
    _end) {
  let
    _length;
  if ( typeof(
         _end) === 'undefined' ) {
    _end =
      _start;
    _start =
      0;
  }
  _length =
    _end -
    _start;
  if ( _length < 0 ) {
    _msg =
      `Second argument 'end' ` +
      `is greater than first ` +
      `argument 'start', returning ` +
      `empty list.`;
    _msg_warning(
      _msg);
    return [];
  }
  return Array(
           _length).keys().map(
             _index =>
               _index + _start);
}

async function
  _run(
    _run_mode,
    _cmd,
    _name,
    _timeout,
    _run_type,
    _method) {
  let
    _array,
    _index,
    _msg,
    _out;
  if ( typeof(
         _cmd) == "undefined" ||
       _cmd == "" ||
       _cmd == [] ) {
    _msg =
      "No command given in input.";
    _msg_error(
        _msg,
        1);
  }
  const
    _program =
      _cmd[
        0];
  const
    _args =
      _cmd.slice(
        1,
        _cmd.length);
  if ( typeof(
         _run_mode) == "undefined" ||
       _run_mode == "" ) {
    _run_mode =
      "sync";
  }
  if ( typeof(
         _name) == "undefined" ||
       _name == "" ) {
    _name =
      "";
  }
  if ( typeof(
         _timeout) == "undefined" ||
       _timeout == "" ) {
    _timeout =
      "0";
  }
  if ( typeof(
         _run_type) == "undefined" ||
       _run_type == "" ) {
    _run_type =
      "spawn";
  }
  if ( typeof(
         _method) == "undefined" ||
       _method == "" ) {
    _method =
      "";
  }
  _msg =
    `Running '${_program}' ` +
    `with arguments '${_args}'.`;
  _msg_info(
    _msg);
  _out =
    "";
  if ( _run_mode == "async" ) {
    // currently not working well id say
    const
      _print =
        function
          (_data) {
          _out = 
            _out +
            _data.toString();
        };
    const
      _close =
        function(
          _code) {
          let
            _array,
            _msg;
          if ( _code != 0 ) {
            _msg =
              `Process exited with code '${_code}'`;
            _msg_error(
              _msg,
              1);
          }
          else {
            _msg =
              `Process exited normally.`;
            _msg_info(
              _msg);
          }
          _array =
            _out.split("\n");
          return _array;
        };
    const
      _process =
        _spawn_async(
          _program,
          _args);
    _process.stdout.on(
      'data',
      _print);
    _process.on(
      'close',
      _close);
    _array =
      _out.split(
        "\n");
    _msg_info(
      _array.length);
    return _array;
  }
  else if ( _run_mode == "sync" ) {
    if ( _run_type == "spawn" ) {
      const
        _process =
          _spawn(
            _program,
            _args,
            { "encoding":
                "utf-8" });
      _array =
        _process.stdout.split(
          "\n");
      return _array;
    }
    else if ( _run_type == "native" ) {
      if ( 0 < _timeout ) {
        _msg_timeout =
          `Timeout of length ` +
          `'${_timeout}' ms reached for task '${_name}'.`;
        _time_over =
          false;
        try {
          const
            _timeout_promise =
              new Promise(
	        (resolve,
                 reject) => {
                  setTimeout(
                    () => {
                      return;
                    },
                    _timeout,
                    "hurr")
                });
          if ( _method != "" ) {
            _out =
              await Promise.race( [
                _sleep(
                  _timeout),
                  _program[
                    _method].apply(
                    _program,
                    _args)
	      ]);
            if ( typeof(
                   _out) == "undefined" ) {
              throw _msg_timeout;
	    }
          }
          else {
            _out =
              await _program.apply(
                _program,
                _args);
          }
        }
        catch(
          _error) {
          _time_over =
            true;
        }
        if ( _time_over ) {
          _msg_warning(
            _msg_timeout);
          return;
        }
        else {
          return _out;
        }
      }
      else {
        _out =
          await _program[
            _method].apply(
            _program,
            _args);
      }
    }
  }
}

function
  _seq(
    _start,
    _end) {
  let
    _item,
    _list;
  _list =
    [];
  if ( _end < _start ) {
    _msg =
      `Second argument 'end' ` +
      `is greater than first ` +
      `argument 'start', returning ` +
      `empty list.`;
    _msg_warning(
      _msg);
    return _list;
  }
  if ( typeof(
         _end) === 'undefined' ) {
    _end =
      _start;
    _start =
      1;
  }
  for ( _item of _range(
                   _start,
                   _end + 1) ) {
    _list.push(
      _item);
  }
  return _list;
}

function
  _sleep(
    _time) {
  return new Promise(
               resolve => setTimeout(
                            resolve,
                            _time));
}

function
  _from_bash_ass_array(
    _bash_array_string) {
  let
    _array,
    _array_name,
    _array_content_re,
    _array_content,
    _array_keys,
    _array_values,
    _key,
    _key_re,
    _keys_matches,
    _keys_re,
    _msg,
    _string,
    _value,
    _value_matches,
    _value_match;
  const
    _array_names =
      [];
  const
    _return =
      {};
  const
    _array_names_re =
      new RegExp(
        `(.+)=\\(`,
        "g");
  const
    _arrays_strings =
      _bash_array_string.match(
        _array_names_re);
  for ( _string of _arrays_strings ) {
    _array_name =
      _string.replace(
        "=(",
        "");
    _array_names.push(
      _array_name);
  }
  for ( _array_name of _array_names ) {
    _return[
      _array_name] =
      {};
    _array_content_re =
      new RegExp(
        `${_array_name}=\\(((.|\n)*?)\\)\n`,
        "g");
    _array_content =
      _bash_array_string.match(
        _array_content_re);
    if ( 1 < _array_content.length ) {
      _msg =
        "Multiple array " +
        `'${_array_name}' definitions ` +
        "detected.";
      _msg_error(
        _msg,
        1);
    }
    else if ( 0 < _array_content.length ) {
      _array =
        _array_content[
          0];
    }
    else {
      _msg =
        "No arrays found in input string.";
      _msg_error(
        _msg,
        1);
    }
    _keys_re =
      new RegExp(
        `\\["(.*?)"\\]`,
        "g");
    _keys_matches =
      _array.match(
        _keys_re);
    _array_keys =
      [];
    for ( _key of _keys_matches ) {
      _key_name =
        _key.replace(
          `["`,
          "");
      _key_name =
        _key_name.replace(
          `"]`,
          "");
      _array_keys.push(
        _key_name);
    }
    for ( _key of _array_keys ) {
      _value_re =
        new RegExp(
          `\\["${_key}"\\]="(.*?)"`,
          "g");
      _value_assignment_matches =
        _array.match(
          _value_re);
      if ( 1 < _value_assignment_matches.length ) {
        _msg =
          "Multiple values " +
          `'${_value_assignment_matches}' assignments found for ` +
          `key '${_key}' of associative array ` +
          `'${_array_name}'.`;
        _msg_error(
          _msg,
          1);
      }
      else if ( 0 < _value_assignment_matches.length ) {
        _value_assignment =
          _value_assignment_matches[
            0];
      }
      else {
        _msg =
          `No values found for key '${_key}'.`;
        _msg_error(
          _msg,
          1);
      }
      _value =
        _value_assignment.replace(
          RegExp(
            `^\\["${_key}"\\]="`,
            "g"),
          "");
      _value =
        _value.replace(
          RegExp(
            `"$`,
            "g"),
          "");
      _return[
        _array_name][
          _key] =
        _value;
    }
  }
  return _return;
}

function
  _to_bash_ass_array(
    _object) {
  let
    _index,
    _key,
    _key_declaration,
    _return;
  _return = [
    "#!/usr/bin/env bash"
  ];
  const
    _arrays_assignments =
      [];
  const
    _arrays_names =
      Object.keys(
        _object);
  const
    _arrays_declaration = [
      "declare \\",
      "  -A \\",
    ];
  const
    _arrays_amount =
      _arrays_names.length;
  const
    _index_max =
      _arrays_amount - 1;
  const
    _indexes =
      _seq(
        0,
        _index_max);
  for ( _index of _indexes ) {
    _array_name =
      _arrays_names[
        _index];
    _array_declaration =
      `  ${_array_name}`;
    if ( _index != _index_max ) {
      _array_declaration +=
        ` \\`;
    }
    _arrays_declaration.push(
      _array_declaration);
    _array_assignment = [
      `${_array_name}=(`
    ];
    _object_keys =
      Object.keys(
        _object[
          _array_name]);
    for ( _key of _object_keys ) {
      _value =
        _object[
          _array_name][
            _key];
      _key_assignment =
        `  ["${_key}"]="${_value}"`;
      _array_assignment.push(
        _key_assignment);
    }
    _array_assignment.push(
      ")");
    _array_assignment_string =
      _array_assignment.join(
        "\n");
    _arrays_assignments.push(
      _array_assignment_string);
  }
  _return =
    _return.concat(
      _arrays_declaration);
  _return =
    _return.concat(
      _arrays_assignments);
  _return =
    _return.join(
      "\n");
  return _return;
}

function
  _get(
    _obj,
    _var) {
  _getter_setter_input_check(
    _obj,
    _var);
  const
    _global =
      _global_get();
  return _global[
    `${_obj}_${_var}`];
}

function
  _getter_setter_input_check(
    _obj,
    _var,
    _value) {
  if ( ( typeof(
           _obj) === "undefined" ||
         _obj == "" ) &&
       ( typeof(
           _var) === "undefined" ||
         _var == "" ) ) {
    const
      _msg =
        "Either one of the 'object' or the " +
        "'variable' arguments must be non-empty";
    _msg_error(
      _msg,
      1);
  }
  if ( typeof(
         _value) === "undefined" ) {
    _value =
      "";
  }
}

/* global
     _process_argv */
const
  _process_argv =
    _argv;

/* global
     _process_chdir */
const
  _process_chdir =
    _cd;

/* global
     _process_cwd */
const
  _process_cwd =
    _cwd;

/* global
     _process_exit */
const
  _process_exit =
    _exit;

/* global
     _process_pwd */
const
  _process_pwd =
    _pwd;

function
  _set(
    _obj,
    _var,
    _value) {
  _getter_setter_input_check(
    _obj,
    _var);
  const
    _global =
      _global_get();
  _global[
    `${_obj}_${_var}`] =
    _value;
}

function
  _globals() {
  /* global
       app_name:
         writable */
  _set(
    "app",
    "name",
    "");
  /* global
       app_opts:
         writable */
  _set(
    "app",
    "opts",
    []);
  /* global
       runtime_environment:
         writable */
  _set(
    "runtime",
    "environment",
    "");
  /* global
       quiet:
         writable */
  const
    _global =
      _global_get();
  _global[
    "quiet"] =
    "y";
}

function
  _override_set(
    _obj,
    _var,
    _default) {
  _getter_setter_input_check(
    _obj,
    _var,
    _default);
  const
    _global =
      _global_get();
  const
    _override =
      _get(
        `override`,
        `${_obj}_${_var}`);
  const
    _override_type =
      typeof(
        _override);
  const
    _override_defined =
      Object.keys(
        _global).includes(
          `override_${_obj}_${_var}`)
  if ( _override_defined ) {
    _set(
      _obj,
      _var,
      _get(
        `override_${_obj}`,
        _var));
  }
  else {
    const
      _value_current =
        _get(
          _obj,
          _var);
    const
      _value_current_type =
        typeof(
          _value_current);
    // if ( _value_current_type != "undefined" &&
    //      _value_current != "" ) {
    //   if ( _default != "" ) {
    //     _set(
    //       _obj,
    //       _var,
    //       _default)
    //   }
    // }
    if ( _value_current_type == "undefined" ||
              _value_current == "" ) {
      // if ( _default != "" ) {
        _set(
          _obj,
          _var,
          _default)
      // }
    }
  }
}

const
  _set_override =
    _override_set;

async function
  _yargv_get(
    _args) {
  let
    _boolean;
  const
    _yargs_opts =
      {};
  const
    _parser_opts =
      {};
  if ( typeof(
          _args) == "undefined" ||
       _args == {} ||
       _args == "" ) {
    _args = {
      "booleans": [],
      "string": true
    };
  }
  const
    _booleans =
      _args[
        "booleans"];
  if ( typeof window === 'undefined' &&
       ( typeof global !== 'undefined' && global.global === global ) ) {
    const
      _yargs =
        await _require(
          "yargs");
    const
      _yargs_helpers_module =
        await _require(
          "yargs/helpers");
    const
      _hide_bin =
        _yargs_helpers_module.hideBin;
    if ( "string" in _args &&
         _args[
           "string"] ) {
      _yargs_opts[
        "_"] = {
        "type":
          "string",
        "string":
          true
      };
      _parser_opts[
        "parse-numbers"] =
        false;
      _parser_opts[
        "parse-positional-numbers"] =
        false;
    }
    if ( _booleans.length > 0 ) {
      for ( _boolean of _booleans) {
        _yargs_opts[
          _boolean] = {
            "demand":
              false,
            "default":
              false,
            "type":
              "boolean",
         };
      }
    }
    if ( 0 < _booleans.length ||
         _args[
           "string"] ) {
      return _yargs(
               _hide_bin(
                 _argv)).parserConfiguration(
                   _parser_opts).options(
                _yargs_opts).string(
                  "_").parse();
    }
    else {
      return _yargs(
        _hide_bin(
          _argv));
    }
  }
}

// ES module export

export {
  _argv,
  _argv_get,
  _argv_url_get,
  _app_name_get,
  _basename,
  _cat,
  _chmod,
  _chown,
  _cmdline_check,
  _chdir,
  _cd,
  _cp,
  _cwd,
  _dir_exists,
  _dirname,
  _display_error,
  _echo,
  _echo2,
  _error_display,
  _exit,
  _ext_rm,
  _file_append,
  _file_exists,
  _file_read,
  _file_write,
  _from_bash_ass_array,
  _fs_worker_new,
  _fs_worker_start,
  _get,
  _get_date_human,
  _get_lib,
  _get_usr,
  _globals,
  _global_get,
  _homedir_get,
  _json_display,
  _json_read,
  _lib_get,
  _ls,
  _mkdir,
  _mktemp,
  _msg_error,
  _msg_info,
  _msg_info_obj,
  _msg_template,
  _msg_warning,
  _mv,
  _override_set,
  _path_join,
  _printf,
  _process_argv,
  _process_chdir,
  _process_cwd,
  _process_exit,
  _process_pwd,
  _pwd,
  _range,
  _require,
  _rm,
  _run,
  _seq,
  _set,
  _set_override,
  _source,
  _sleep,
  _spawn_async,
  _spawn,
  _split,
  _stat,
  _to_bash_ass_array,
  _usr_get,
  _yargv_get
};

// Common Javascript export

// module.exports = {
//   _argv:
//     _argv,
//   _argv_get:
//     _argv_get,
//   _argv_url_get:
//     _argv_url_get,
//   _app_name_get:
//     _app_name_get,
//   _basename:
//     _basename,
//   _cat:
//     _cat,
//   _chmod:
//     _chmod,
//   _chown:
//     _chown,
//   _cmdline_check:
//     _cmdline_check,
//   _chdir:
//     _chdir,
//   _cd:
//     _cd,
//   _cp:
//     _cp,
//   _cwd:
//     _cwd,
//   _dir_exists:
//     _dir_exists,
//   _dirname:
//     _dirname,
//   _display_error:
//     _display_error,
//   _echo:
//     _echo,
//   _echo2:
//     _echo2,
//   _error_display:
//     _display_error,
//   _exit:
//     _exit,
//   _ext_rm:
//     _ext_rm,
//   _file_append:
//     _fs_utils_module._file_append,
//   _file_exists:
//     _file_exists,
//   _file_read:
//     _file_read,
//   _file_write:
//     _file_write,
//   _from_bash_ass_array:
//     _from_bash_ass_array,
//   _fs_worker_new:
//     _fs_worker_new,
//   _fs_worker_start:
//     _fs_worker_start,
//   _get:
//     _get,
//   _get_date_human:
//     _get_date_human,
//   _get_lib:
//     _lib_get,
//   _get_usr:
//     _usr_get,
//   _globals:
//     _globals,
//   _global_get:
//     _global_get,
//   _homedir_get:
//     _homedir_get,
//   _json_display:
//     _json_display,
//   _json_read:
//     _json_read,
//   _lib_get:
//     _lib_get,
//   _ls:
//     _ls,
//   _mkdir:
//     _mkdir,
//   _mktemp:
//     _mktemp,
//   _msg_error:
//     _msg_error,
//   _msg_info:
//     _msg_info,
//   _msg_info_obj:
//     _msg_info_obj,
//   _msg_template:
//     _msg_template,
//   _msg_warning:
//     _msg_warning,
//   _mv:
//     _mv,
//   _override_set:
//     _override_set,
//   _path_join:
//     _path_join,
//   _printf:
//     _printf,
//   _process_argv:
//     _process_argv,
//   _process_chdir:
//     _process_chdir,
//   _process_cwd:
//     _process_cwd,
//   _process_exit:
//     _process_exit,
//   _process_pwd:
//     _process_pwd,
//   _pwd:
//     _pwd,
//   _range:
//     _range,
//   _require:
//     _require,
//   _rm:
//     _rm,
//   _run:
//     _run,
//   _seq:
//     _seq,
//   _set:
//     _set,
//   _set_override:
//     _set_override,
//   _source:
//     _source,
//   _sleep:
//     _sleep,
//   _spawn_async:
//     _spawn_async,
//   _spawn:
//     _spawn,
//   _split:
//     _split,
//   _stat:
//     _stat,
//   _to_bash_ass_array:
//     _to_bash_ass_array,
//   _usr_get:
//     _usr_get,
//   _yargv_get:
//     _yargv_get
// };
