#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later

/**    ----------------------------------------------------------------
 *     fs-utils
 *     ----------------------------------------------------------------
 *     Copyright ©
 *       Pellegrino Prevete
 *         2024, 2025, 2026
 * 
 *     All rights reserved
 *     ----------------------------------------------------------------
 * 
 *     This program is free software: you can redistribute it and/or
 *     modify it under the terms of the GNU General Public License as
 *     published by the Free Software Foundation, either version 3 of
 *     the License, or (at your option) any later version.
 * 
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the GNU General Public
 *     License along with this program.
 *     If not, see <https://www.gnu.org/licenses/>.
 */

const
  _utils_module =
    require(
      "./utils");
const
  _os_tmpdir_get =
    _utils_module._os_tmpdir_get;
const
  _fs_module =
    require(
      "fs");
const
  _fs_read_dir_sync =
      _fs_module.readdirSync;
const
  _fs_exists_sync =
    _fs_module.existsSync;
const
  _fs_append_file_sync =
    _fs_module.appendFileSync;
const
  _fs_read_file_sync =
    _fs_module.readFileSync;
const
  _fs_write_file_sync =
    _fs_module.writeFileSync;
const
  _fs_worker_new =
    _fs_module.fsWorkerNew;
const
  _fs_worker_start =
    _fs_module.fsWorkerStart;
const
  _mkdtemp =
    _fs_module.mkdtemp;
const
  _stat =
    _fs_module.statSync;
const
  _json_parse =
    JSON.parse;
const
  _json_display =
    JSON.stringify;
const
  _path_module =
    require(
      "path");
const
  _path_module_basename =
    _path_module.basename;
const
  _path_module_dirname =
    _path_module.dirname;
const
  _path_module_join =
    _path_module.join;
const
  _path_module_parse =
    _path_module.parse;

function
  _basename(
    _file_path) {
  let
    _dir;
  _dir =
    _path_module_basename(
      _file_path);
  return _dir;
}

function
  _dirname(
    _file_path) {
  let
    _dir;
  _dir =
    _path_module_dirname(
      _file_path);
  return _dir;
}

function
  _ext_rm(
    _path) {
  let
    _dir,
    _name,
    _paths;
  _dir =
    _path_module_parse(
      _path).dir;
  _name =
    _path_module_parse(
      _path).name;
  _paths = [
    _dir,
    _name];
  return _path_join(
    _paths); 
}

function
  _file_exists(
    _path) {
  let
    _exists,
    _return;
  _return =
    false;
  _exists =
    _fs_exists_sync(
      _path);
  if (_exists) {
    _return =
      true;
  }
  return _return;
}

function
  _file_read(
    _path,
    _read_opts) {
    _return;
  const
    _read_opts_type =
      typeof(
        _read_opts_type);
  if ( _read_opts_type === "undefined" ||
       _read_opts == {} ||
       _read_opts == "" ) {
    _read_opts =
      {"encoding":
         "utf8",
       "flag":
         'r'};
  }
  const
    _return =
      _fs_read_file_sync(
        _path,
        _read_opts);
  return _return;
}

function
  _file_append(
    _path,
    _content,
    _append) {
  _fs_append_file_sync(
    _path,
    _content);
}

function
  _file_write(
    _path,
    _content,
    _append) {
  _fs_write_file_sync(
    _path,
    _content);
}

function
  _json_read(
    _json_path) {
  let
    _json_str,
    _json;
  _json_str =
    _file_read(
      _json_path);
  _json =
    _json_parse(
      _json_str);
  return _json;
}

function
  _ls(
    _args) {
  const
    _return =
      _fs_read_dir_sync.apply(
        null,
        [_args]);
  return _return;
} 

function
  _path_join(
    _paths) {
  let
    _path;
  _path =
    _path_module_join.apply(
      null,
      _paths);
  return _path;
}

async function
_mktemp(
  _prefix,
  _directory) {
  const
    _directory_type =
      typeof(
        _directory);
  if ( typeof(
         _prefix) == "undefined" ||
       _prefix == "" ) {
    const
      _os_tmpdir =
        _os_tmpdir_get();
    _prefix =
      `${_os_tmpdir}/`;
  }
  if ( _directory_type == "undefined" ||
       _directory == "" ||
       _directory == "true" ) {
    _directory =
      true;
  }
  if ( _directory == "false" ) {
    _directory =
      false;
  }
  if ( _directory ) {
    try {
      const
        _dir =
          await _mkdtemp(
            _prefix);
      _msg =
        `Created directory '${_dir}'.`;
      _msg_info(
        _msg);
      return _dir;
    }
    catch(
      _error) {
      throw _error;
    }
  }
  else {
    _msg =
      "It only supports creating " +
      "temporary directories.";
    _msg_error(
      _msg,
      1);
  }
}

module.exports = {
  _basename:
    _basename,
  _cat:
    _file_read,
  _dirname:
    _dirname,
  _ext_rm:
    _ext_rm,
  _file_append:
    _file_append,
  _file_exists:
    _file_exists,
  _file_read:
    _file_read,
  _file_write:
    _file_write,
  _fs_worker_new:
    _fs_worker_new,
  _fs_worker_start:
    _fs_worker_start,
  _json_display:
    _json_display,
  _json_read:
    _json_read,
  _ls:
    _ls,
  _mkdir:
    _fs_module.mkdirSync,
  _mktemp:
    _mktemp,
  _mv:
    _fs_module.renameSync,
  _path_join:
    _path_join,
  _rm:
    _fs_module.rmSync,
  _stat:
    _stat
};
