#!/usr/bin/env node

//
// SPDX-License-Identifier: AGPL-3.0-or-later
//

const
  _fs =
    require(
      "fs");
const
  _path =
    require(
      'path');


function
  _basename(
    _file_path) {
  let
    _dir;
  _dir =
    _path.basename(
      _file_path);
  return _dir;
}


function
  _dirname(
    _file_path) {
  let
    _dir;
  _dir =
    _path.dirname(
      _file_path);
  return _dir;
}


function
  _file_exists(
    _path) {
  let
    _exists,
    _return;
  _return =
    false;
  _exists =
    _fs.existsSync(
      _path);
  if (_exists) {
    _return =
      true;
  }
  return _return;
}


function
  _file_read(
    _path) {
  let
    _read_opts,
    _return;
  _read_opts =
   {"encoding":
      "utf8",
    "flag":
      'r'};
  _return =
    _fs.readFileSync(
      _path,
      _read_opts);
  return _return;
}


function
  _file_write(
    _path,
    _content) {
  _fs.writeFileSync(
    _path,
    _content);
}


module.exports = {
  _basename:
    _basename,
  _dirname:
    _dirname,
  _file_exists:
    _file_exists,
  _file_read:
    _file_read,
  _file_write:
    _file_write,
};
