#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later

/**    ----------------------------------------------------------------
 *     utils
 *     ----------------------------------------------------------------
 *     Copyright ©
 *       Pellegrino Prevete
 *         2024, 2025, 2026
 * 
 *     All rights reserved
 *     ----------------------------------------------------------------
 * 
 *     This program is free software: you can redistribute it and/or
 *     modify it under the terms of the GNU General Public License as
 *     published by the Free Software Foundation, either version 3 of
 *     the License, or (at your option) any later version.
 * 
 *     This program is distributed in the hope that it will be useful,
 *     but WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *     GNU General Public License for more details.
 * 
 *     You should have received a copy of the GNU General Public License
 *     along with this program.
 *     If not, see <https://www.gnu.org/licenses/>.
 */

const
  _process_module =
    await import(
      "process");
/* global
     _argv */
const
  _argv =
    _process_module.argv;
/* global
     _exit */
const
  _exit =
    _process_module.exit;
/* global
     _cd */
const
  _cd =
    _process_module.chdir;
/* global
     _cwd */
const
  _cwd =
    _process_module.cwd;
/* global
     _pwd */
const
  _pwd =
    _cwd;
/* global
     _stdout */
const
  _stdout =
    _process_module.stdout;

function
  _argv_url_get(
    _key_name) {
  let
    _argv,
    _assignment,
    _assignments,
    _key,
    _key_value,
    _location,
    _msg,
    _url,
    _value;
  if ( typeof(
         _key_name) === 'undefined' ||
       _key_name == "" ||
       _key_name == null ) {
    _msg =
      "Getting all values.";
    _msg_info(
      _msg);
    _key_name =
      "";
  }
  _argv =
    [];
  _location =
    window.location;
  _url =
    _location.search.substring(
      1);
  _assignments =
    _url.split(
      '&');
  for ( let
          _result =
            0;
        _result <
          _assignments.length;
        _result++ ) {
    _assignment =
      _assignments[
        _result];
    _key_value =
      _assignment.split(
        '=');
    _key =
      _key_value[
        0];
    if ( _key == _key_name ||
         _key_name == "" ) {
      _value =
        _key_value[
          1];
      _argv.push(
        _value);
    }
  }
  return _argv;
}

function
  _global_get() {
  let
    _global;
  if ( typeof window === 'undefined' &&
       ( typeof global !== 'undefined' && global.global === global ) &&
       typeof __webpack_require__ !== 'function' ) {
    _global =
      global;
  }
  if ( typeof(
         window) != "undefined" ) {
    _global =
      window;
  }
  return _global;
}

function
  _display_error(
    _error) {
  let
    _message;
  if ( typeof(error) == "object" ) {
    if ( 'error' in _error && 
         _error[
           'error'] != undefined &&
         'message' in _error[
                        'error'] ) {
      _message =
        _error[
          'error'][
            'message'];
    }
    else if ( 'shortMessage' in _error ) {
      _message =
        _error[
          'shortMessage'];
    }
    else {
      _message =
        _error;
    }
    console.error(
      _error);
  }
  else {
    _message =
      _error;
    console.error(
      _error);
  }
  _msg_error(
    _message,
    0);
}

const
  _error_display =
    _display_error;

function 
  _msg_template(
    _type,
    _app_name) {
  let
    _template;
  if ( typeof(
         _app_name) == "undefined" ||
       _app_name == "" ) {
    _template =
      `${_type}: {_msg}`;
  }
  else if ( typeof(
              _app_name) == "string" ||
            _app_name != "" ) {
      _template =
        `[${_app_name}] ${_type}: {_msg}`;
  }
  return _template;
}

function
  _msg_warning(
    _msg) {
  let
    _out;
  const
    _global =
      _global_get();
  const
    _app_name =
      _global[
        "app_name"];
  if ( quiet == "n" ) {
    _template =
      _msg_template(
        "WARNING",
        _app_name);
    _out =
      _template.replaceAll(
        "{_msg}",
        _msg);
    console.warn(
      _out);
  }
}

function
  _msg_info(
    _msg) {
  let
    _out;
  if ( typeof(
         quiet) == "undefined" ||
       quiet == "" ) {
    quiet =
      "y";
  }
  if ( quiet == "n" ) {
    const
      _template =
        _msg_template(
          "INFO",
          app_name);
    _out =
      _template.replaceAll(
        "{_msg}",
        _msg);
    console.log(
      _out);
  }
}

function
  _msg_error(
    _msg,
    _exit_code) {
  let
    _app_name,
    _template,
    _out;
  const
    _global =
      _global_get();
  _app_name =
    _global[
      "app_name"];
  if ( typeof(
         _app_name) == "undefined" ||
         _app_name == "" ) {
    _app_name =
      "";
  }
  _exit_code =
    String(
      _exit_code);
  _template =
    _msg_template(
      "ERROR",
      _app_name);
  _out =
    _template.replaceAll(
      "{_msg}",
      _msg);
  if ( _exit_code === "1" ) {
    console.error(
      _out);
    _exit(
      1);
  }
  else if ( _exit_code === "0" ) {
    console.warn(
      _out);
  }
}

function 
  _msg_info_obj(
    _name,
    _obj) {
  let
    _template,
    _partial,
    _msg;
  _msg =
    `${_name}: '${_obj}'`;
  _msg_info(
    _msg);
}

// ES module export

export {
  _argv,
  _argv_url_get,
  _cd,
  _cwd,
  _display_error,
  _error_display,
  _exit,
  _global_get,
  _msg_error,
  _msg_info,
  _msg_info_obj,
  _msg_template,
  _msg_warning,
  _pwd,
  _stdout
};

// Common Javascript export

// module.exports = {
//   _argv:
//     _argv,
//   _argv_url_get:
//     _argv_url_get,
//   _cd:
//     _cd,
//   _cwd:
//     _cwd,
//   _display_error:
//     _display_error,
//   _error_display:
//     _error_display,
//   _exit:
//     _exit,
//   _global_get:
//     _global_get,
//   _msg_error:
//     _msg_error,
//   _msg_info:
//     _msg_info,
//   _msg_info_obj:
//     _msg_info_obj,
//   _msg_template:
//     _msg_template,
//   _msg_warning:
//     _msg_warning,
//   _pwd:
//     _pwd,
//   _stdout:
//     _stdout,
// };
