#!/usr/bin/env node

// SPDX-License-Identifier: AGPL-3.0-or-later

//    ----------------------------------------------------------------------
//    Copyright © 2024, 2025  Pellegrino Prevete
//
//    All rights reserved
//    ----------------------------------------------------------------------
//
//    This program is free software: you can redistribute it and/or modify
//    it under the terms of the GNU Affero General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    This program is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU Affero General Public License for more details.
//
//    You should have received a copy of the GNU Affero General Public License
//    along with this program.  If not, see <https://www.gnu.org/licenses/>.

const
  _libcrash =
  require(
    '../crash-js/crash-js');
_cmdline_check =
  _libcrash._cmdline_check;
_error_display =
  _libcrash._error_display;
_ext_rm =
  _libcrash._ext_rm;
_file_read =
  _libcrash._file_read;
_file_write =
  _libcrash._file_write;
_json_read =
  _libcrash._json_read;
_msg_info =
  _libcrash._msg_info;
_msg_error =
  _libcrash._msg_error;

function
  _global_variables() {
  app_name =
    "ahsi";
}

_global_variables();

quiet =
  "n";

_msg_info(
  "ciao");
